-keep class com.beantechs.** { *; }
-keep class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**
-keep class okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class moe.shizuku.** { *; }
-keep class rikka.shizuku.** { *; }
-keepattributes *Annotation*
